from activity25_1 import *
from activity25_2 import *
import time

print("COMPILATION")
time.sleep(1)
print("Generated By Roberto B. Guevarra Jr.")
time.sleep(1)
print("BSIT-1A")
time.sleep(1)

def count_down():
    print("\nThis Program ends in 5secs.......")
    for i in range(1,5):
        print(i)
        time.sleep(1)

def activity():
    while True:
            print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
            print("___________________________________________________________________________________________") 
            print("|                                     Prelims  Menu:                                      |") 
            print("|_________________________________________________________________________________________|") 
            print("|             1.Activity 1                   |             16.Activity 16                 |") 
            print("|             2.Activity 2                   |             17.Activity 17                 |") 
            print("|             3.Activity 3                   |             18.Activity 18                 |") 
            print("|             4.Activity 4                   |             19.Activity 19                 |") 
            print("|             5.Activity 5                   |             20.Activity 20                 |") 
            print("|             6.Activity 6                   |             21.Activity 21                 |")  
            print("|             7.Activity 7                   |             22.Activity 22                 |") 
            print("|             8.Activity 8                   |             23.Activity 23                 |") 
            print("|             9.Activity 9                   |             19.Activity 19                 |") 
            print("|             10.Activity 10                 |             20.Activity 20                 |") 
            print("|             11.Activity 11                 |             21.Activity 21                 |") 
            print("|             12.Activity 12                 |             22.Activity 22                 |") 
            print("|             13.Activity 13                 |             23.Activity 23                 |") 
            print("|             14.Activity 14                 |             0.Back to Main Menu            |") 
            print("|             15.Activity 15                 |                                            |") 
            print("|____________________________________________|____________________________________________|") 
            activity_number = int(input("Enter the activity number: "))
            if activity_number == 0:
                print("\n\nReturning to Main Menu.")
                main_menu()
                break
            elif activity_number <= 100:
                if activity_number == 1:
                    act1()
                    count_down()
                elif activity_number == 2:
                    act2()
                    count_down()
                elif activity_number == 3:
                    act3()
                    count_down()
                elif activity_number == 4:
                    act4()
                    count_down()
                elif activity_number == 5:
                    act5()
                    count_down()
                elif activity_number == 6:
                    act6()
                    count_down()
                elif activity_number == 7:
                    act7()
                    count_down()
                elif activity_number == 8:
                    act8()
                    count_down()
                elif activity_number == 9:
                    act9()
                    count_down()
                elif activity_number == 10:
                    act10()
                    count_down()
                elif activity_number == 11:
                    act11()
                    count_down()
                elif activity_number == 12:
                    act12()
                    count_down()
                elif activity_number == 13:
                    act13()
                    count_down()
                elif activity_number == 14:
                    act14()
                    count_down()
                elif activity_number == 15:
                    act15()
                    count_down()
                elif activity_number == 16:
                    act16()
                    count_down()
                elif activity_number == 17:
                    act17()
                    count_down()
                elif activity_number == 18:
                    act18()
                    count_down()
                elif activity_number == 19:
                    act19()
                    count_down()
                elif activity_number == 20:
                    act20()
                    count_down()
                elif activity_number == 21:
                    act21()
                    count_down()
                else:
                    print("Invaled")


def code_challenge():
    while True:
            print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
            print("______________________________________________") 
            print("|             Code Challenge                 |") 
            print("|                                            |") 
            print("|             1.Code Challenge 1             |") 
            print("|             2.Code Challenge 2             |") 
            print("|             3.Code Challenge 3             |") 
            print("|             4.Code Challenge 4             |") 
            print("|             5.Code Challenge 5             |") 
            print("|             6.Code Challenge 6             |")  
            print("|             7.Code Challenge 7             |") 
            print("|             8.Code Challenge 8             |") 
            print("|             9.Code Challenge 9             |") 
            print("|             10.Code Challenge 10           |") 
            print("|             11.Code Challenge 11           |") 
            print("|             12.Code Challenge 12           |") 
            print("|             13.Code Challenge 13           |") 
            print("|             14.Code Challenge 14           |") 
            print("|             15.Code Challenge 15           |")
            print("|             0.Back to Main Menu            |")
            print("|____________________________________________|") 
            Code_Challenge_number = int(input("Enter the Code Challenge number: "))
            if Code_Challenge_number == 0:
                print("\n\nReturning to Main Menu.")
                main_menu()
                break
            elif Code_Challenge_number <= 100:
                if Code_Challenge_number == 1:
                    code1()
                    count_down()
                elif Code_Challenge_number == 2:
                    code2()
                    count_down()
                elif Code_Challenge_number == 3:
                    code3()
                    count_down()
                elif Code_Challenge_number == 4:
                    code4()
                    count_down()
                elif Code_Challenge_number == 5:
                    code5()
                    count_down()
                elif Code_Challenge_number == 6:
                    code6()
                    count_down()
                elif Code_Challenge_number == 7:
                    code7()
                    count_down()
                elif Code_Challenge_number == 8:
                    code8()
                    count_down()
                elif Code_Challenge_number == 9:
                    code9()
                    count_down()
                elif Code_Challenge_number == 10:
                    code10()
                    count_down()
                elif Code_Challenge_number == 11:
                    code11()
                    count_down()
                elif Code_Challenge_number == 12:
                    code12()
                    count_down()
                elif Code_Challenge_number == 13:
                    code13()
                    count_down()
                elif Code_Challenge_number == 14:
                    code14()
                    count_down()
                elif Code_Challenge_number == 15:
                    code15()
                    count_down()
                else:
                    print("Invaled")
                


def main_menu():
       while True:
        print(" ____________________________________________")         
        print("|                 Main Menu:                 |") 
        print("|____________________________________________|") 
        print("|                 1.Activity                 |") 
        print("|                 2.Code Challenge           |") 
        print("|                 0.Exit                     |") 
        print("|____________________________________________|") 
        choice = int(input("Enter your choice: "))
        if choice == 1:
             activity()
        elif choice == 2:
             code_challenge()
        elif choice == 0:
            exit()
        else:
            print("Invaled")
main_menu()

